const GAMES_DATA = [
  {id:0,name:"Bowmasters",file:"0.html",cat:"Action",icon:"🏹"},
  {id:1,name:"OvO",file:"1.html",cat:"Platformer",icon:"🏃"},
  {id:2,name:"OvO 2",file:"2.html",cat:"Platformer",icon:"🏃"},
  {id:3,name:"OvO 3 Dimensions",file:"3.html",cat:"Platformer",icon:"🏃"},
  {id:5,name:"Ice Dodo",file:"5.html",cat:"Arcade",icon:"🐦"},
  {id:6,name:"Block Blast",file:"6.html",cat:"Puzzle",icon:"🧩"},
  {id:7,name:"Jetpack Joyride",file:"7.html",cat:"Action",icon:"🚀"},
  {id:8,name:"Friday Night Funkin",file:"8-a.html",cat:"Rhythm",icon:"🎤"},
  {id:9,name:"Sprunki",file:"9.html",cat:"Music",icon:"🎵"},
  {id:10,name:"Temple Run 2",file:"10.html",cat:"Runner",icon:"🏃"},
  {id:11,name:"Stickman Hook",file:"11.html",cat:"Arcade",icon:"🪝"},
  {id:12,name:"Subway Surfers",file:"12.html",cat:"Runner",icon:"🛹"},
  {id:14,name:"Bridge Race",file:"14.html",cat:"Racing",icon:"🌉"},
  {id:17,name:"Magic Tiles 3",file:"17.html",cat:"Rhythm",icon:"🎹"},
  {id:19,name:"Supreme Duelist",file:"19.html",cat:"Fighting",icon:"⚔️"},
  {id:23,name:"Pou",file:"23.html",cat:"Virtual Pet",icon:"🟤"},
  {id:24,name:"Crossy Road",file:"24.html",cat:"Arcade",icon:"🐔"},
  {id:25,name:"Basket Battle",file:"25.html",cat:"Sports",icon:"🏀"},
  {id:27,name:"Geometry Dash Lite",file:"27.html",cat:"Rhythm",icon:"🔷"},
  {id:28,name:"Basketball Frvr",file:"28.html",cat:"Sports",icon:"🏀"},
  {id:33,name:"Retro Bowl",file:"33.html",cat:"Sports",icon:"🏈"},
  {id:34,name:"Retro Bowl College",file:"34.html",cat:"Sports",icon:"🏈"},
  {id:35,name:"Drive Mad",file:"35.html",cat:"Racing",icon:"🚗"},
  {id:38,name:"Five Nights at Freddy's",file:"38.html",cat:"Horror",icon:"🐻"},
  {id:39,name:"Five Nights at Freddy's 2",file:"39.html",cat:"Horror",icon:"🐻"},
  {id:40,name:"Five Nights at Freddy's 3",file:"40.html",cat:"Horror",icon:"🐻"},
  {id:41,name:"Five Nights at Freddy's 4",file:"41.html",cat:"Horror",icon:"🐻"},
  {id:45,name:"Vex 1",file:"45.html",cat:"Platformer",icon:"🏃"},
  {id:47,name:"Vex 3",file:"47.html",cat:"Platformer",icon:"🏃"},
  {id:49,name:"Vex 4",file:"49.html",cat:"Platformer",icon:"🏃"},
  {id:50,name:"Vex 5",file:"50.html",cat:"Platformer",icon:"🏃"},
  {id:57,name:"Monkey Mart",file:"57.html",cat:"Simulation",icon:"🐒"},
  {id:58,name:"1v1.LoL",file:"58.html",cat:"Shooter",icon:"🔫"},
  {id:63,name:"Angry Birds",file:"63.html",cat:"Puzzle",icon:"🐦"},
  {id:64,name:"Backrooms",file:"64.html",cat:"Horror",icon:"🚪"},
  {id:65,name:"Baldi's Basics",file:"65.html",cat:"Horror",icon:"📏"},
  {id:66,name:"Basket Random",file:"66.html",cat:"Sports",icon:"🏀"},
  {id:67,name:"Big Tower Tiny Square",file:"67.html",cat:"Platformer",icon:"🔲"},
  {id:70,name:"BitLife",file:"70.html",cat:"Simulation",icon:"👶"},
  {id:77,name:"Boxing Random",file:"77.html",cat:"Sports",icon:"🥊"},
  {id:81,name:"Cluster Rush",file:"81.html",cat:"Action",icon:"🚛"},
  {id:82,name:"Cookie Clicker",file:"82-aa.html",cat:"Idle",icon:"🍪"},
  {id:85,name:"Cut the Rope",file:"85.html",cat:"Puzzle",icon:"✂️"},
  {id:86,name:"Draw Climber",file:"86.html",cat:"Arcade",icon:"✏️"},
  {id:90,name:"Granny",file:"90.html",cat:"Horror",icon:"👵"},
  {id:92,name:"Gun Mayhem 2",file:"92.html",cat:"Shooter",icon:"🔫"},
  {id:93,name:"Hangman",file:"93.html",cat:"Puzzle",icon:"📝"},
  {id:99,name:"Moto X3M",file:"99.html",cat:"Racing",icon:"🏍️"},
  {id:101,name:"Paper.io 2",file:"101.html",cat:"Arcade",icon:"📄"},
  {id:108,name:"Slope",file:"108.html",cat:"Skill",icon:"🟢"},
  {id:114,name:"Snow Rider 3D",file:"114.html",cat:"Racing",icon:"🎿"},
  {id:116,name:"Smash Karts",file:"116.html",cat:"Racing",icon:"🏎️"},
  {id:117,name:"Tank Trouble",file:"117.html",cat:"Shooter",icon:"🔫"},
  {id:118,name:"Tetris",file:"118.html",cat:"Puzzle",icon:"🧩"},
  {id:120,name:"Tiny Fishing",file:"120.html",cat:"Simulation",icon:"🎣"},
  {id:121,name:"Tunnel Rush",file:"121.html",cat:"Skill",icon:"🌀"},
  {id:122,name:"2048",file:"122.html",cat:"Puzzle",icon:"🔢"},
  {id:125,name:"Among Us",file:"125.html",cat:"Multiplayer",icon:"🧑‍🚀"},
  {id:130,name:"Minecraft Classic",file:"130.html",cat:"Sandbox",icon:"⛏️"},
  {id:148,name:"Drift Hunters",file:"148.html",cat:"Racing",icon:"🏎️"},
  {id:152,name:"Pac-Man",file:"152.html",cat:"Arcade",icon:"🟡"},
  {id:153,name:"Snake",file:"153.html",cat:"Arcade",icon:"🐍"},
  {id:160,name:"Flappy Bird",file:"160.html",cat:"Arcade",icon:"🐦"},
  {id:167,name:"Wordle",file:"167.html",cat:"Puzzle",icon:"📝"},
  {id:172,name:"Chess",file:"172.html",cat:"Strategy",icon:"♟️"},
  {id:180,name:"Tic Tac Toe",file:"180.html",cat:"Strategy",icon:"❌"},
  {id:202,name:"Google Dinosaur",file:"202.html",cat:"Arcade",icon:"🦕"},
  {id:253,name:"Chat Bot (AI)",file:"253.html",cat:"Tool",icon:"🤖"},
  {id:257,name:"Google Baseball",file:"257.html",cat:"Sports",icon:"⚾"},
  {id:261,name:"Fruit Ninja",file:"261.html",cat:"Arcade",icon:"🍉"},
  {id:264,name:"Escape Road",file:"264.html",cat:"Racing",icon:"🚗"},
  {id:265,name:"Escape Road 2",file:"265.html",cat:"Racing",icon:"🚗"},
  {id:267,name:"Pizza Tower",file:"267.html",cat:"Platformer",icon:"🍕"},
  {id:268,name:"Bacon May Die",file:"268.html",cat:"Action",icon:"🥓"},
  {id:272,name:"Basketball Stars",file:"272.html",cat:"Sports",icon:"🏀"},
  {id:276,name:"Drift Boss",file:"276.html",cat:"Racing",icon:"🏎️"},
  {id:278,name:"Madalin Stunt Cars 2",file:"278.html",cat:"Racing",icon:"🏎️"},
  {id:283,name:"Rooftop Snipers",file:"283.html",cat:"Shooter",icon:"🔫"},
  {id:285,name:"Basket Bros",file:"285.html",cat:"Sports",icon:"🏀"},
  {id:294,name:"Idle Dice",file:"294.html",cat:"Idle",icon:"🎲"},
  {id:297,name:"Minecraft 1.5.2",file:"297.html",cat:"Sandbox",icon:"⛏️"},
  {id:302,name:"Little Runmo",file:"302.html",cat:"Platformer",icon:"🍄"},
  {id:303,name:"Territorial.io",file:"303.html",cat:"Strategy",icon:"🗺️"},
  {id:308,name:"Nazi Zombies",file:"308.html",cat:"Shooter",icon:"🧟"},
  {id:309,name:"Sandboxels",file:"309.html",cat:"Sandbox",icon:"🏖️"},
  {id:310,name:"Dreadhead Parkour",file:"310.html",cat:"Platformer",icon:"🏃"},
  {id:316,name:"Angry Birds Chrome",file:"316.html",cat:"Puzzle",icon:"🐦"},
  {id:325,name:"Kitchen Bazar",file:"325.html",cat:"Simulation",icon:"🍳"},
  {id:329,name:"Om Nom Run",file:"329.html",cat:"Runner",icon:"🟢"},
  {id:333,name:"Fancy Pants Adventure",file:"333.html",cat:"Platformer",icon:"👖"},
  {id:338,name:"Getaway Shootout",file:"338.html",cat:"Action",icon:"🔫"},
  {id:339,name:"House of Hazards",file:"339.html",cat:"Action",icon:"🏠"},
  {id:350,name:"Binding of Isaac",file:"350.html",cat:"Roguelike",icon:"😢"},
  {id:354,name:"Adventure Capitalist",file:"354.html",cat:"Idle",icon:"💰"},
  {id:361,name:"Google Feud",file:"361.html",cat:"Puzzle",icon:"🔍"},
  {id:362,name:"Idle Breakout",file:"362.html",cat:"Idle",icon:"🧱"},
  {id:365,name:"JustFall.lol",file:"365.html",cat:"Multiplayer",icon:"⬇️"},
  {id:370,name:"Smash Karts",file:"370.html",cat:"Racing",icon:"🏎️"},
  {id:435,name:"A Small World Cup",file:"435.html",cat:"Sports",icon:"⚽"},
  {id:436,name:"Awesome Tanks",file:"436.html",cat:"Shooter",icon:"🔫"},
  {id:440,name:"Celeste PICO",file:"440.html",cat:"Platformer",icon:"🍓"},
  {id:449,name:"City Smash",file:"449.html",cat:"Action",icon:"🏙️"},
  {id:450,name:"Amanda the Adventurer",file:"450.html",cat:"Horror",icon:"📺"},
  {id:451,name:"Slender: The 8 Pages",file:"451.html",cat:"Horror",icon:"👤"},
  {id:456,name:"Undertale Yellow",file:"456.html",cat:"RPG",icon:"💛"},
  {id:461,name:"Slither.io",file:"461.html",cat:"Multiplayer",icon:"🐍"},
  {id:464,name:"Choppy Orc",file:"464.html",cat:"Platformer",icon:"🪓"},
  {id:465,name:"Cuphead",file:"465.html",cat:"Action",icon:"☕"},
  {id:468,name:"Hollow Knight",file:"468.html",cat:"Action",icon:"🗡️"},
  {id:470,name:"Doodle Jump",file:"470.html",cat:"Arcade",icon:"📱"},
  {id:472,name:"Bad Time Simulator",file:"472.html",cat:"Action",icon:"💀"},
  {id:501,name:"Kindergarten 3",file:"501.html",cat:"Adventure",icon:"🎒"},
  {id:505,name:"Pokemon Red",file:"505.html",cat:"RPG",icon:"🔴"},
  {id:506,name:"Pokemon Emerald",file:"506.html",cat:"RPG",icon:"💚"},
  {id:507,name:"The Impossible Quiz",file:"507.html",cat:"Puzzle",icon:"❓"},
  {id:508,name:"Super Mario Bros",file:"508.html",cat:"Platformer",icon:"🍄"},
  {id:512,name:"Final Earth 2",file:"512.html",cat:"Strategy",icon:"🌍"},
  {id:544,name:"Plinko",file:"544.html",cat:"Arcade",icon:"⚪"},
  {id:547,name:"Baseball Bros",file:"547.html",cat:"Sports",icon:"⚾"},
  {id:548,name:"Football Bros",file:"548.html",cat:"Sports",icon:"🏈"},
  {id:554,name:"Yandere Simulator",file:"554.html",cat:"Simulation",icon:"🎀"},
  {id:557,name:"Getting Over It",file:"557.html",cat:"Platformer",icon:"🏔️"},
  {id:581,name:"BuildNow.gg",file:"581.html",cat:"Shooter",icon:"🔫"},
  {id:585,name:"Fallout",file:"585.html",cat:"RPG",icon:"☢️"},
  {id:586,name:"The Oregon Trail",file:"586.html",cat:"Adventure",icon:"🐂"},
  {id:588,name:"Super Mario 64",file:"588.html",cat:"Platformer",icon:"🍄"},
  {id:595,name:"Shapez.io",file:"595.html",cat:"Strategy",icon:"🔷"},
  {id:597,name:"Plants vs Zombies 2",file:"597.html",cat:"Strategy",icon:"🌻"},
  {id:602,name:"Doom 2",file:"602.html",cat:"Shooter",icon:"💀"},
  {id:611,name:"Zelda: Ocarina of Time",file:"611.html",cat:"RPG",icon:"🗡️"},
  {id:612,name:"Zelda: Majora's Mask",file:"612.html",cat:"RPG",icon:"🎭"},
  {id:617,name:"Postal",file:"617-a.html",cat:"Action",icon:"📮"},
];
